# Generated by Django 6.1.1 on 2026-10-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vechicle_No', models.CharField()),
                ('Name', models.CharField()),
                ('Address', models.TextField()),
                ('Mobile', models.IntegerField()),
                ('DoB', models.DateField()),
                ('Received_Date', models.DateField()),
                ('Vechicle_Type', models.CharField()),
            ],
        ),
    ]
